import Foundation
import XCTest
@testable import NetnyahooImportCore

/// Fixtures are generated by `fixtures/generate.py` (synthetic data only).
enum Fixtures {
  static let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
    .appendingPathComponent("fixtures", isDirectory: true)
  static let home = root.appendingPathComponent("home", isDirectory: true)
  static let support = root.appendingPathComponent("home/Library/Application Support", isDirectory: true)

  static func url(_ path: String) -> URL { root.appendingPathComponent(path) }
  static func support(_ path: String) -> URL { support.appendingPathComponent(path) }

  static var secrets: [String: String] {
    let data = try! Data(contentsOf: url("secrets.json"))
    return try! JSONSerialization.jsonObject(with: data) as! [String: String]
  }

  static var chromiumSecret: Data { Data(secrets["chromiumSafeStorageSecret"]!.utf8) }
  static var chromiumKey: Data { ChromiumCrypto.deriveKey(secret: chromiumSecret) }

  /// Pretends Chrome, Arc, Dia, Firefox, Safari, Brave, Opera and Helium are installed; Edge is not.
  static func discovery() -> BrowserDiscovery {
    BrowserDiscovery(
      applicationSupport: support,
      locateApp: { ids in
        let installed = ["com.google.Chrome", "company.thebrowser.Browser", "company.thebrowser.dia",
                         "org.mozilla.firefox", "com.apple.Safari", "com.brave.Browser",
                         "com.operasoftware.Opera", "net.imput.helium"]
        return ids.first(where: installed.contains).map { URL(fileURLWithPath: "/Applications/\($0).app") }
      },
      iconFor: { _, id in "/tmp/icons/\(id).png" }
    )
  }
}

/// Collects progress events and history chunks from an import.
final class Recorder: @unchecked Sendable {
  private let lock = NSLock()
  private(set) var events: [ImportProgress] = []
  private(set) var chunks: [[HistoryEntry]] = []

  func observer(chunkSize: Int = 1000, stream: Bool = true, onEvent: @escaping @Sendable (ImportProgress) -> Void = { _ in }) -> ImportObserver {
    let progress: @Sendable (ImportProgress) -> Void = { [self] e in
      lock.withLock { events.append(e) }
      onEvent(e)
    }
    var history: (@Sendable ([HistoryEntry]) -> Void)?
    if stream {
      history = { [self] chunk in lock.withLock { chunks.append(chunk) } }
    }
    return ImportObserver(chunkSize: chunkSize, progress: progress, history: history)
  }
}

extension BookmarkNode {
  /// Compact outline for assertions: "Folder[child, child]" / "title<url>".
  var outline: String {
    switch type {
    case .url: "\(title)<\(url ?? "")>"
    case .folder: "\(title)\(role.map { "{\($0)}" } ?? "")[\((children ?? []).map(\.outline).joined(separator: ", "))]"
    }
  }
}
