#!/usr/bin/env node
// JS/React benchmark for Netnyahoo on a production (Hermes) bundle.
//
//   node js-bench.mjs bundle <outDir>
//       Builds the production JS bundle of the current tree (metro, --dev false) and compiles it with
//       hermesc, as the Release build does. Prints sizes and the biggest packages.
//   node js-bench.mjs run --app <Release Netnyahoo.app> --bundle <main.jsbundle> --label <name>
//                         [--runs 5] [--scenarios a,b] [--port 47817] [--out <dir>]
//       Clones the app (APFS clone), swaps in the bundle, and for each run seeds a fresh data folder
//       (seed.mjs: 200 tabs, 5000 history entries, 1000 bookmarks), launches a hidden instance, runs
//       the scenarios of bench-app.js through the dev harness and quits it. Writes <label>.json.
//   node js-bench.mjs compare <before.json> <after.json>
//       Prints a before/after table of medians.
//
// The app side is the opt-in probe in src/lib/perfProbe.ts, on only when the data folder holds a
// `perf-probe` file (the seed writes one).

import { execFileSync, spawnSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { createServer } from "node:http";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeSeed } from "./seed.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, "../..");
const repo = resolve(appDir, "../..");
const defaultOut = process.env.NN_PERF_OUT ?? "/tmp/nn-perf-js";

const [command, ...rest] = process.argv.slice(2);
const flags = {};
const positional = [];
for (let i = 0; i < rest.length; i++) {
  if (rest[i].startsWith("--")) flags[rest[i].slice(2)] = rest[++i];
  else positional.push(rest[i]);
}

const median = (xs) => {
  const s = xs.filter((x) => typeof x === "number" && Number.isFinite(x)).sort((a, b) => a - b);
  if (!s.length) return null;
  const m = s.length >> 1;
  return s.length % 2 ? s[m] : (s[m - 1] + s[m]) / 2;
};
const pct = (xs, p) => {
  const s = xs.filter(Number.isFinite).sort((a, b) => a - b);
  return s.length ? s[Math.min(s.length - 1, Math.floor(p * s.length))] : null;
};
const sum = (o) => Object.values(o ?? {}).reduce((a, b) => a + b, 0);
const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

// MARK: Bundle

function bundle(outDir) {
  mkdirSync(outDir, { recursive: true });
  const js = join(outDir, "main.js");
  const hbc = join(outDir, "main.jsbundle");
  const rn = join(repo, "node_modules/react-native-macos");
  execFileSync(
    process.execPath,
    [
      join(rn, "scripts/bundle.js"), "bundle", "--entry-file", "index.js", "--platform", "macos", "--dev", "false",
      "--minify", "false", "--bundle-output", js, "--sourcemap-output", `${js}.map`, "--assets-dest", join(outDir, "assets"),
      "--config-cmd", `'${process.execPath}' '${join(rn, "cli.js")}' config`,
    ],
    { cwd: appDir, stdio: ["ignore", "ignore", "inherit"] },
  );
  const hermesc = join(appDir, "macos/Pods/hermes-engine/destroot/bin/hermesc");
  execFileSync(hermesc, ["-emit-binary", "-max-diagnostic-width=80", "-O", "-out", hbc, js], { stdio: "inherit" });
  const sizes = { js: statSync(js).size, hbc: statSync(hbc).size, packages: packageSizes(js) };
  writeFileSync(join(outDir, "sizes.json"), JSON.stringify(sizes, null, 2));
  console.log(`JS ${(sizes.js / 1024).toFixed(0)} KB, Hermes bytecode ${(sizes.hbc / 1024).toFixed(0)} KB`);
  for (const [name, bytes] of Object.entries(sizes.packages).slice(0, 15)) console.log(`  ${(bytes / 1024).toFixed(0).padStart(6)} KB  ${name}`);
  return sizes;
}

// Generated bytes per package, from the source map.
function packageSizes(js) {
  const map = JSON.parse(readFileSync(`${js}.map`, "utf8"));
  const lines = readFileSync(js, "utf8").split("\n");
  const chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  const decode = (seg) => {
    const out = [];
    let value = 0;
    let shift = 0;
    for (const ch of seg) {
      const d = chars.indexOf(ch);
      value += (d & 31) << shift;
      if (d & 32) shift += 5;
      else {
        out.push(value & 1 ? -(value >> 1) : value >> 1);
        value = 0;
        shift = 0;
      }
    }
    return out;
  };
  const bytes = new Array(map.sources.length).fill(0);
  let source = 0;
  map.mappings.split(";").forEach((line, row) => {
    let col = 0;
    const segs = line ? line.split(",").map(decode) : [];
    const cols = segs.map((seg) => (col += seg[0]));
    const length = lines[row]?.length ?? 0;
    segs.forEach((seg, i) => {
      if (seg.length < 2) return;
      source += seg[1];
      bytes[source] += Math.max(0, (cols[i + 1] ?? length) - cols[i]);
    });
  });
  const byPackage = {};
  map.sources.forEach((src, i) => {
    const m = /node_modules\/((?:@[^/]+\/)?[^/]+)/.exec(src);
    const key = m ? m[1] : /(apps\/browser\/src|packages\/[^/]+)/.exec(src)?.[1] ?? "other";
    byPackage[key] = (byPackage[key] ?? 0) + bytes[i];
  });
  return Object.fromEntries(Object.entries(byPackage).sort((a, b) => b[1] - a[1]));
}

// MARK: Test server

const PNG = Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==", "base64");

function startServer(port) {
  const server = createServer((req, res) => {
    const url = new URL(req.url, "http://localhost");
    if (url.pathname.startsWith("/img/") || url.pathname === "/favicon.ico") {
      const delay = Number(url.searchParams.get("d") ?? 0);
      return void setTimeout(() => {
        res.writeHead(200, { "content-type": "image/png", "cache-control": "no-store" });
        res.end(PNG);
      }, delay);
    }
    if (url.pathname === "/heavy") {
      const run = url.searchParams.get("run") ?? "";
      const images = Array.from({ length: 40 }, (_, i) => `<img src="/img/${i}?d=${40 + ((i * 37) % 900)}&r=${run}" width=40 height=40>`).join("");
      res.writeHead(200, { "content-type": "text/html", "cache-control": "no-store" });
      return void res.end(`<!doctype html><html><head><meta name="theme-color" content="#336699"><title>Loading ${run}</title>
<link rel="icon" href="/favicon.ico?d=300&r=${run}"></head><body><h1>Heavy page</h1>${images}
<script>let n=0;const t=setInterval(()=>{document.title='Heavy '+(++n);if(n>=5)clearInterval(t)},150);</script></body></html>`);
    }
    const name = url.pathname.split("/").pop();
    res.writeHead(200, { "content-type": "text/html", "cache-control": "no-store" });
    res.end(`<!doctype html><html><head><title>Page ${name}</title></head><body><p>${name}</p></body></html>`);
  });
  return new Promise((resolve, reject) => {
    server.once("error", reject);
    server.listen(port, "127.0.0.1", () => resolve(server));
  });
}

// MARK: App instances

function pidsOf(binary) {
  const r = spawnSync("ps", ["-ww", "-ax", "-o", "pid=", "-o", "command="], { encoding: "utf8", timeout: 5000 });
  return r.stdout
    .split("\n")
    .map((l) => /^\s*(\d+)\s+(.*)$/.exec(l))
    .filter((m) => m && (m[2] === binary || m[2].startsWith(`${binary} `)))
    .map((m) => Number(m[1]));
}
const alive = (pid) => {
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
};

async function launch(app, dataDir, port) {
  const binary = join(app, "Contents/MacOS/Netnyahoo");
  if (pidsOf(binary).length) throw new Error(`an instance of ${app} is already running`);
  const launchedAt = Date.now();
  execFileSync("open", [
    "-g", "-n", "--env", "NETNYAHOO_BACKGROUND=1", "--env", `NETNYAHOO_DATA_DIR=${dataDir}`,
    "--env", `NETNYAHOO_REMOTE_DEBUGGING_PORT=${port}`, app,
  ]);
  for (let i = 0; i < 200; i++) {
    const [pid] = pidsOf(binary);
    if (pid) return { pid, launchedAt };
    await sleep(50);
  }
  throw new Error("app did not start");
}

async function quit(pid) {
  if (!alive(pid)) return;
  process.kill(pid, "SIGTERM");
  for (let i = 0; i < 150 && alive(pid); i++) await sleep(100);
  if (alive(pid)) process.kill(pid, "SIGKILL");
}

let evalSeq = 0;
async function evaluate(dataDir, pid, body, timeoutMs = 120_000) {
  const id = `bench-${process.pid}-${++evalSeq}`;
  writeFileSync(join(dataDir, "dev-eval.js"), `// ${id}\n${body}`);
  const file = join(dataDir, "dev-eval-result.json");
  const end = Date.now() + timeoutMs;
  while (Date.now() < end) {
    if (!alive(pid)) throw new Error("app exited");
    if (existsSync(file)) {
      try {
        const out = JSON.parse(readFileSync(file, "utf8"));
        if (out.id === id) {
          if (out.error) throw new Error(`in app: ${out.error}`);
          return out.result;
        }
      } catch (error) {
        if (String(error).includes("in app:")) throw error;
      }
    }
    await sleep(50);
  }
  throw new Error(`timed out: ${body.slice(0, 80)}`);
}

// MARK: Run

const ALL = ["startup", "persistence", "idle", "typing", "switchTabs", "openClose", "scroll", "pageLoad", "hover", "profileSwipe"];

async function run() {
  const { app, bundle: jsbundle, label, runs = "5", port = "47817", out = defaultOut } = flags;
  if (!app || !jsbundle || !label) throw new Error("run needs --app, --bundle and --label");
  const scenarios = flags.scenarios ? flags.scenarios.split(",") : ALL;
  const clone = join(out, "apps", label, "Netnyahoo.app");
  rmSync(dirname(clone), { recursive: true, force: true });
  mkdirSync(dirname(clone), { recursive: true });
  execFileSync("cp", ["-cR", app, clone]);
  cpSync(jsbundle, join(clone, "Contents/Resources/main.jsbundle"));
  const version = execFileSync("/usr/libexec/PlistBuddy", ["-c", "Print CFBundleShortVersionString", join(clone, "Contents/Info.plist")], { encoding: "utf8" }).trim();
  const origin = `http://127.0.0.1:${port}`;
  const server = await startServer(Number(port));
  const lib = readFileSync(join(here, "bench-app.js"), "utf8");
  const results = [];
  try {
    for (let r = 0; r < Number(runs); r++) {
      const dataDir = join(out, "data", `${label}-${r}`);
      rmSync(dataDir, { recursive: true, force: true });
      writeSeed(dataDir, origin, version);
      const { pid, launchedAt } = await launch(clone, dataDir, 9500 + r + (label.length % 50) * 10);
      const result = { run: r, launchedAt };
      try {
        // The harness ignores a script that was already there when it started; ping until it answers.
        let ready = false;
        for (let i = 0; i < 30 && !ready; i++) ready = await evaluate(dataDir, pid, "return 1;", 2000).then(() => true, (e) => (String(e).includes("exited") ? Promise.reject(e) : false));
        if (!ready) throw new Error("dev harness never answered");
        await evaluate(dataDir, pid, lib, 60_000);
        for (const name of scenarios) {
          process.stderr.write(`[${label} ${r}] ${name}\n`);
          // --trace 1 names anonymous timer callbacks by their call sites (slower; for finding, not timing).
          const options = JSON.stringify({ origin, scenario: name });
          const entry = flags.trace && name !== "startup" ? "traced" : name;
          result[name] = await evaluate(dataDir, pid, `return nnBench.run(${JSON.stringify(entry)}, ${options});`);
        }
      } finally {
        await quit(pid);
      }
      results.push(result);
    }
  } finally {
    server.close();
  }
  const bundleSize = statSync(jsbundle).size;
  const report = { label, version, bundle: jsbundle, bundleSize, when: new Date().toISOString(), results, summary: summarize(results, bundleSize) };
  const file = join(out, `${label}.json`);
  writeFileSync(file, JSON.stringify(report, null, 2));
  printSummary(report.summary);
  console.log(`\nwrote ${file}`);
}

// MARK: Summary

// Host wrappers render whenever their parent does; the detail lists the app's own components.
const HOST = /^(View|Text|Pressable|Image|ScrollView|TextInput|InternalTextInput|Animated\(.*\)|Netnyahoo.*|Surface|Symbol|MouseArea|ContextMenuArea|FadeLabel|VirtualizedList.*|CellRenderer.*)$/;
const appOnly = (counter) => Object.fromEntries(Object.entries(counter ?? {}).filter(([k]) => !HOST.test(k)));

const top = (counter, n = 6) =>
  Object.entries(counter ?? {})
    .sort((a, b) => b[1] - a[1])
    .slice(0, n)
    .map(([k, v]) => `${k} ${Math.round(v)}`)
    .join(", ");

function statLine(stats) {
  return {
    commits: stats.commits,
    renders: sum(stats.renders),
    mounts: sum(stats.mounts),
    hostUpdates: stats.hostUpdates,
    storeUpdates: stats.storeUpdates?.browser ?? 0,
    // Module-level store subscribers only (components subscribe through zustand's internal api).
    listenerMs: sum(stats.listenerMs),
    listenerCalls: sum(stats.listenerCalls),
    taskMs: sum(stats.taskMs),
    tasks: sum(stats.tasks),
    writes: sum(stats.writes),
    writeKB: sum(stats.writeBytes) / 1024,
    writeMs: sum(stats.writeMs),
    walkMs: stats.walkMs,
  };
}

function summarize(results, bundleSize) {
  const pick = (fn) => results.map((r) => {
    try {
      return fn(r);
    } catch {
      return null;
    }
  });
  const m = (fn) => {
    const xs = pick(fn).filter((x) => x !== null && x !== undefined);
    return { median: median(xs), min: xs.length ? Math.min(...xs) : null, max: xs.length ? Math.max(...xs) : null, n: xs.length };
  };
  const lines = {};
  const add = (key, fn) => (lines[key] = m(fn));
  const statKeys = (key, fn) => {
    for (const k of ["commits", "renders", "hostUpdates", "storeUpdates", "listenerMs", "taskMs", "writes", "writeKB"]) add(`${key}.${k}`, (r) => statLine(fn(r))[k]);
  };
  lines["bundle.hbcKB"] = { median: bundleSize / 1024, min: bundleSize / 1024, max: bundleSize / 1024, n: 1 };
  add("startup.launchToBundleMs", (r) => r.startup.marks.bundleStart - r.launchedAt);
  add("startup.bundleEvalMs", (r) => r.startup.marks.bundleEnd - r.startup.marks.bundleStart);
  add("startup.bundleToFirstCommitMs", (r) => r.startup.marks.firstCommit - r.startup.marks.bundleStart);
  add("startup.bundleToFirstWindowMs", (r) => r.startup.marks.firstWindow - r.startup.marks.bundleStart);
  add("startup.launchToFirstWindowMs", (r) => r.startup.marks.firstWindow - r.launchedAt);
  statKeys("startup", (r) => r.startup.stats);
  add("persist.historyStringifyMs", (r) => r.persistence.history.ms);
  add("persist.historyKB", (r) => r.persistence.history.bytes / 1024);
  add("persist.sessionStringifyMs", (r) => r.persistence.session.ms);
  add("persist.bookmarksStringifyMs", (r) => r.persistence.bookmarks.ms);
  statKeys("idle10s", (r) => r.idle.stats);
  add("idle10s.timerCallbacks", (r) => sum(Object.fromEntries(Object.entries(r.idle.stats.timers).filter(([k]) => !k.includes("pollDevEval")))));
  add("typing.keyMedianMs", (r) => median(r.typing.keys));
  add("typing.keyP95Ms", (r) => pct(r.typing.keys, 0.95));
  add("typing.keyMaxMs", (r) => Math.max(...r.typing.keys));
  statKeys("typing30", (r) => r.typing.stats);
  // JS time the app spent beyond the measured steps themselves (effects, timers, promise work, events).
  const beyond = (stats, steps) => statLine(stats).taskMs - steps.reduce((a, b) => a + b, 0);
  add("typing30.otherJsMs", (r) => beyond(r.typing.stats, r.typing.keys));
  add("switch.medianMs", (r) => median(r.switchTabs.steps));
  add("switch12.otherJsMs", (r) => beyond(r.switchTabs.stats, r.switchTabs.steps));
  add("open20.otherJsMs", (r) => beyond(r.openClose.openStats, r.openClose.open));
  add("close20.otherJsMs", (r) => beyond(r.openClose.closeStats, r.openClose.close));
  add("hover24.otherJsMs", (r) => beyond(r.hover.stats, r.hover.steps));
  statKeys("switch12", (r) => r.switchTabs.stats);
  add("open.medianMs", (r) => median(r.openClose.open));
  add("close.medianMs", (r) => median(r.openClose.close));
  statKeys("open20", (r) => r.openClose.openStats);
  statKeys("close20", (r) => r.openClose.closeStats);
  statKeys("scroll", (r) => r.scroll.stats);
  add("pageLoad.loadMs", (r) => median(r.pageLoad.runs.map((x) => x.loadMs)));
  for (const k of ["commits", "renders", "hostUpdates", "storeUpdates", "listenerMs", "taskMs", "writes", "writeKB"])
    add(`pageLoad.${k}`, (r) => median(r.pageLoad.runs.map((x) => statLine(x.stats)[k])));
  add("hover.medianMs", (r) => median(r.hover.steps));
  statKeys("hover24", (r) => r.hover.stats);
  add("profileSwipe.commandMs", (r) => median(r.profileSwipe.runs.map((x) => x.ms)));
  for (const k of ["commits", "renders", "hostUpdates", "taskMs"])
    add(`profileSwipe.${k}`, (r) => median(r.profileSwipe.runs.map((x) => statLine(x.stats)[k])));

  // What renders most, from the last run, for reading.
  const last = results.at(-1) ?? {};
  const detail = {};
  const put = (key, stats) => stats && (detail[key] = { renders: top(appOnly(stats.renders), 12), storeKeys: top(stats.storeKeys, 8), tasks: top(stats.tasks, 8), taskMs: top(stats.taskMs, 6), timers: top(stats.timers, 8), timerMs: top(stats.timerMs, 8), writes: top(stats.writeBytes, 5) });
  put("idle", last.idle?.stats);
  put("typing", last.typing?.stats);
  put("switchTabs", last.switchTabs?.stats);
  put("open", last.openClose?.openStats);
  put("close", last.openClose?.closeStats);
  put("scroll", last.scroll?.stats);
  put("pageLoad", last.pageLoad?.runs?.at(-1)?.stats);
  put("hover", last.hover?.stats);
  put("profileSwipe", last.profileSwipe?.runs?.[0]?.stats);
  put("startup", last.startup?.stats);
  return { lines, detail };
}

const fmt = (v) => (v === null || v === undefined ? "–" : Math.abs(v) >= 100 ? v.toFixed(0) : v.toFixed(1));

function printSummary(summary) {
  for (const [key, v] of Object.entries(summary.lines)) console.log(`${key.padEnd(36)} ${fmt(v.median).padStart(9)}   [${fmt(v.min)}–${fmt(v.max)}] n=${v.n}`);
  for (const [key, d] of Object.entries(summary.detail)) {
    console.log(`\n${key}`);
    for (const [k, v] of Object.entries(d)) if (v) console.log(`  ${k}: ${v}`);
  }
}

function compare(a, b) {
  const A = JSON.parse(readFileSync(a, "utf8")).summary.lines;
  const B = JSON.parse(readFileSync(b, "utf8")).summary.lines;
  console.log(`| metric | before | after | change |\n|---|---:|---:|---:|`);
  for (const key of Object.keys(A)) {
    const x = A[key]?.median;
    const y = B[key]?.median;
    const change = x && y !== null && y !== undefined ? `${(((y - x) / x) * 100).toFixed(0)}%` : "";
    console.log(`| ${key} | ${fmt(x)} [${fmt(A[key].min)}–${fmt(A[key].max)}] | ${fmt(y)} [${fmt(B[key]?.min)}–${fmt(B[key]?.max)}] | ${change} |`);
  }
}

if (command === "bundle") bundle(positional[0] ?? join(defaultOut, "bundle"));
else if (command === "run") await run();
else if (command === "compare") compare(positional[0], positional[1]);
else if (command === "summary") printSummary(JSON.parse(readFileSync(positional[0], "utf8")).summary);
else {
  console.error("usage: js-bench.mjs bundle <outDir> | run --app … --bundle … --label … | compare <a.json> <b.json> | summary <a.json>");
  process.exit(64);
}
