"""Pack the offline game into one self-contained HTML file.

Usage: python3 inline.py <out.html>

The engine serves the result in place of Chrome's dino page
(packages/cef/patches/chromium-neterror-yahu.patch), and step 5 of the CEF
build regenerates it, so ../offline-game stays the source: CSS, scripts and
the manifest go inline, every WebP becomes a data: URL in window.YAHU_ASSETS
(read by game.js), and the CSP allows exactly those inline blocks by hash.

The embedder fills the JSON block `<script type="application/json"
id="yahu-error">null</script>` with {"code": …, "url": …}; a hashed bootstrap
copies it to window.YAHU_ERROR. Without it the page runs standalone.
Python 3 standard library only.
"""

import base64
import hashlib
import re
import sys
from pathlib import Path

GAME = Path(__file__).resolve().parent.parent / "offline-game"

CSP = (
    "default-src 'none'; img-src data: blob:; style-src {styles}; script-src {scripts}; "
    "connect-src 'none'; font-src 'none'; media-src 'none'; object-src 'none'; "
    "frame-src 'none'; base-uri 'none'; form-action 'none'"
)
ERROR_BLOCK = '<script type="application/json" id="yahu-error">null</script>'
BOOTSTRAP = 'window.YAHU_ERROR = JSON.parse(document.getElementById("yahu-error").textContent);'


def source_hash(text: str) -> str:
    return "'sha256-" + base64.b64encode(hashlib.sha256(text.encode()).digest()).decode() + "'"


def inline_block(tag: str, text: str) -> str:
    # Nothing may close the element early; the data URLs and our own code never do.
    assert f"</{tag}" not in text.lower(), f"</{tag} inside inlined {tag}"
    return f"<{tag}>{text}</{tag}>"


def main():
    out = Path(sys.argv[1])
    html = (GAME / "index.html").read_text()
    css = (GAME / "game.css").read_text()
    manifest = (GAME / "assets" / "manifest.js").read_text()
    game = (GAME / "game.js").read_text()

    assets = []
    for path in sorted((GAME / "assets").rglob("*.webp")):
        rel = path.relative_to(GAME).as_posix()
        data = base64.b64encode(path.read_bytes()).decode()
        assets.append(f'"{rel}":"data:image/webp;base64,{data}"')
    assets_js = "window.YAHU_ASSETS = {" + ",".join(assets) + "};\n" + manifest

    scripts = [BOOTSTRAP, assets_js, game]
    csp = CSP.format(styles=source_hash(css), scripts=" ".join(source_hash(s) for s in scripts))

    def replace(pattern: str, repl: str):
        nonlocal html
        html, n = re.subn(pattern, lambda _: repl, html)
        assert n == 1, f"index.html: expected one match for {pattern}"

    replace(r'<meta http-equiv="Content-Security-Policy" content="[^"]*">',
            f'<meta http-equiv="Content-Security-Policy" content="{csp}">')
    replace(r'<link rel="stylesheet" href="game.css">', inline_block("style", css))
    replace(r'<script src="assets/manifest.js"></script>',
            ERROR_BLOCK + inline_block("script", BOOTSTRAP) + inline_block("script", assets_js))
    replace(r'<script src="game.js"></script>', inline_block("script", game))
    html = html.replace("<!doctype html>", "<!doctype html>\n<!-- Generated by offline-game-pipeline/inline.py. Do not edit. -->", 1)

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html)
    print(f"{out}: {len(html.encode()) / 1e6:.2f} MB, {len(assets)} images")


if __name__ == "__main__":
    main()
